### ISSUE TITLE
live_delivery status is missing the status response message

### ISSUE THREAD

**Issue by shaileshp0110** [FabioPinheiro/scala-did#209]
For the DIDComm message status, the "live_delivery" status should initially be set to false within the response messages for the status message type URI: https://didcomm.org/messagepickup/3.0/status. 
To activate live mode, a "live-delivery-change" message needs to be sent. 
Following the dispatch of the "live-delivery-change" message, the "live_delivery" status in subsequent responses should be set to true.

**Comment by FabioPinheiro** [comment]
Seems like the 'live_delivery' is field is optional in the status message.
Should we make this feel not optional?

https://github.com/FabioPinheiro/scala-did/blob/master/did/shared/src/main/scala/fmgp/did/comm/protocol/pickup3/Status.scala#L36

**Comment by FabioPinheiro** [comment]
Maybe we should only improve the mediator and make it false there

**Comment by shaileshp0110** [comment]
Closing this as it is more on the mediator implementation the change is needed, Not responsibility of library
